### ISSUE TITLE
Push 0.2.3 to Github

### ISSUE THREAD

**Issue by asomers** [DonaldWhyte/double#21]
It looks like you published version 0.2.3 on 9-Feb-2019, but forgot to push the changes to GitHub.  Could you please?

**Comment by asomers** [comment]
ping.  Could you please push your latest changes to GitHub?

**Comment by DonaldWhyte** [comment]
This has been done. The only actual change was updating the version in Cargo.toml to 0.2.3. The source code in 0.2.3 is the same as the current `master` branch of this Git repo.

Apologies for the long delay.
